name: run-tests
run-name: (${{ github.actor }}) Run linters and unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - pyproject.toml
      - 'src/**'
  push:
    paths:
      - pyproject.toml
      - 'src/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: ./.github/actions/setup-environment/  # the trailing slash is important!
        with:
          python-version: 3.11
      - name: Check import order (isort)
        run: poetry run isort --check --diff src/
      - name: Check code format (flake8)
        run: poetry run flake8
      - name: Static analysis (pylint)
        run: poetry run pylint src/
